# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "uat" ]
  pull_request:
    branches: [ "uat" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: 'Docker Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
 
      -  name: Build the frontend image and push it to ACR
         uses: docker/build-push-action@v2
         with:
          push: true
          tags: aftab70.azurecr.io/myapache:${{ github.run_number }}
          file: Dockerfile
          
      - name: ‘Login to Azure’
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      
          
      -  name: 'Deploy to Azure Container Instances'
         uses: 'azure/aci-deploy@v1'
         with:
          resource-group: TestGroup
          dns-name-label: aftab70
          image: aftab70.azurecr.io/myapache:${{ github.run_number }}
          cpu: 1
          memory: 1
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: aftabwebserver
          location: 'central india'     
